server:
  port: 10000
spring:
  application:
    name: gateway1
  cloud:
    gateway:
      routes:
        - id: INFORMATION-SERVICE
          uri: lb://INFORMATION-SERVICE
          predicates:
            - Path=/information/**
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
        - id: TRADE-SERVICE
          uri: lb://TRADE-SERVICE
          predicates:
            - Path=/trade/**
        - id: RESOURCES-SERVICE
          uri: lb://RESOURCES-SERVICE
          predicates:
            - Path=/resources/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.161:8761/eureka,http://192.168.0.161:8762/eureka #eureka服务器地址
  instance:
    prefer-ip-address: true
    appname: gateway1

feign:
  hystrix:
    enabled: true